language: python
python:
  - "2.7"

install:
  - pip install tox

env:
  - TOX_ENV=test

script:
  - tox -e $TOX_ENV

notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#nameko
    use_notice: true
    skip_join: true

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: FI//lZjo1hx/t1treOa85vEWOn7bsaw7bCuKGUsoB8MuC+9QEuabyLDxdHQ6BoPMSIbWh95pVC+6OCXzr+NuWzF2syvarwfBl/Q2DqDx2CV2j+pYh6NKRoH22tZfyLua1POYGVyYrK6hyphlDyZScuKcBfSjQdIFsxU21EJgorw=
  on:
    tags: true
    repo: onefinestay/nameko-socket-server
